### PR TITLE
Feature 2 is developed, please review

### PR DESCRIPTION
**Pull request by techworldwithsiva**
Feature 2 is developed, please review

### CODE REVIEW

**Comment by sivakumarreddym** [comment]
check once again

**Comment by techworldwithsiva** [comment]
> check once again
yes checked once again, it seems good

**Comment by sivakumarreddym** [comment]
few more code is missing, add forgot password feature too

**Comment by techworldwithsiva** [comment]
> few more code is missing, add forgot password feature too

added that feature you asked

**Review by sivakumarreddym — APPROVED** [review]
everything is good, approving

**Pull request merged**
